import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div id="app">
      <Head>
        <title>My sunshine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main />

      <footer></footer>
    </div>
  );
}
